apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-hpa
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`hpa.example.com`)
    kind: Rule
    services:
      - name: hpa-php-svc
        port: 80
  tls:
    certResolver: myresolver
 
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-host1
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`host1.example.com`)
    kind: Rule
    services:
    - name: host1-svc
      port: 80
  tls:
    certResolver: myresolver

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutet-host2
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`host2.example.com`)
    kind: Rule
    services:
    - name: host2-svc
      port: 80
  tls:
    certResolver: myresolver

